IF "%CONFIG_DEFINED%" == "1" GOTO :EOF
SET CRI_NAME=dockerd
SET CRI_IMAGES_PAUSE=mcr.microsoft.com/k8s/core/pause:1.2.0
SET CRI_IMAGES_NANOSERVER=mcr.microsoft.com/windows/nanoserver:1809
SET CRI_IMAGES_SERVERCORE=mcr.microsoft.com/windows/servercore:ltsc2019

SET CNI_NAME=flannel
SET CNI_SOURCE_NAME0=flanneld
SET CNI_SOURCE_URL0=https://github.com/coreos/flannel/releases/download/v0.11.0/flanneld.exe
SET CNI_PLUGIN_NAME=vxlan
SET CNI_INTERFACENAME=Ethernet

SET KUBERNETES_SOURCE_RELEASE=1.16.3
SET KUBERNETES_SOURCE_URL=https://dl.k8s.io/v1.16.3/kubernetes-node-windows-amd64.tar.gz

SET KUBERNETES_CONTROLPLANE_IPADDRESS=192.168.0.240
SET KUBERNETES_CONTROLPLANE_USERNAME=root
SET KUBERNETES_CONTROLPLANE_KUBEADMTOKEN=q0bi1q.wuslke69tcu5kp64
SET KUBERNETES_CONTROLPLANE_KUBEADMCAHASH=sha256:2e42cccc763ab3744db01bae729e2246bb471c4c334c7ae560db4fdc00b92ac3
SET KUBERNETES_KUBEPROXY_GATES_WINOVERLAY=true"
SET KUBERNETES_NETWORK_SERVICECIDR=10.233.0.0/18
SET KUBERNETES_NETWORK_CLUSTERCIDR=10.233.64.0/18
SET INSTALL_DESTINATION=C:\ProgramData\Kubernetes

SET KUBECONFIG="C:\k\etc\kubernetes\admin.conf"

REM fix it
SET CLUSTER_CIDR=%KUBERNETES_NETWORK_CLUSTERCIDR%
SET SERVICE_CIDR=%KUBERNETES_NETWORK_SERVICECIDR%

SET PATH=%PATH%;c:\k\bin;c:\k\sbin

SET CNI_PLUGINS_URL=https://github.com/containernetworking/plugins/releases/download/v0.8.3/cni-plugins-windows-amd64-v0.8.3.tgz
SET CONFIG_DEFINED=1
